### ISSUE TITLE
mvp cleanup

### ISSUE THREAD

**Issue by fkymy** [yshkd/ofton-rails#19]
## Todo
- [x] validation msgs
- [x] scss structure
- [x] Foundation Layout Objects

## Others
- [x] logo
- [x] index flexbox sometimes breaks
- [x] images (anon user)
- [x] author(anon user)
- [x] pagination
- [x] breadcrumbs

## References

https://stackoverflow.com/questions/36952578/in-rails-how-to-display-errors-in-my-comment-form-after-i-submit-it

https://stackoverflow.com/questions/4779963/how-can-i-access-my-localhost-from-my-android-device
